name = "abhay"
print(len(name))
print(name.startswith("a"))
print(name.endswith("y"))   
print(name.isalpha())
print(name.isdigit())
print(name.islower())
print(name.isupper())
print(name.upper())
print(name.lower())
print(name.replace("a","A"))
print(name.split("h"))
print(name.find("h"))
print(name.count("a"))
print(name.center(10))
print(name.center(10,"*"))
